//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dotnetFinalProjectWinForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblGame
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblGame()
        {
            this.TblMoves = new HashSet<TblMoves>();
        }
    
        public int GameId { get; set; }
        public System.DateTime GameDate { get; set; }
        public int Result { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMoves> TblMoves { get; set; }
    }
}
