//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dotnetFinalProjectWinForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMoves
    {
        public int MoveId { get; set; }
        public int GameId { get; set; }
        public int FromRow { get; set; }
        public int FromCol { get; set; }
        public int ToRow { get; set; }
        public int ToCol { get; set; }
        public int PieceType { get; set; }
        public int MoveNumber { get; set; }
    
        public virtual TblGame TblGame { get; set; }
    }
}
